### ISSUE TITLE
Epic: Course Browser component

### ISSUE THREAD

**Issue by 2rickspencer** [2rickspencer/uky_base_theme#1]

**Comment by 2rickspencer** [comment]
Strategy: Utilize uky_base_theme+configured core Views module+Custom content-type.

- [ ] Input: Custom content-type for collecting course information
- [ ] Output: View with two displays - custom CSS profiles for each
- [ ] Toggle: Use Views / Header / Link to Display to create Display toggle between HTML List and Grid-based displays with custom list view
